version: 0.1

phases:

  install:
    commands:
      - "npm install -g mocha"

  pre_build:
    commands:
      - "npm install --production"

  build:
    commands:
      - "mocha"

  post_build:
    commands:
      - "cat .manifest | xargs tar czf bundle.tgz"

artifacts:
  files:
    - bundle.tgz
    - .manifest
