# Here be a service
---
name: RPC.TestService
version: 2017.05.05-101740
description: Testing Service

main: src/index.js

configurations:

  - name: shared
    key: /config/shared
    # - logLevel
    # - stackName
